#!/bin/sh

# This script will rotate and compress old log files generated by cf_logsclient.py
# Project at https://github.com/jewnix/cloudflare-logsclient
#
# By David Twersky
# Jan 20 2020
# jewunix@gmail.com

# Find files older than 1 hour
old_files=`find /var/log/cloudflare_logs -type f  ! -mmin -60`

# Compress old files
for i in $old_files; do
  gzip $i
  logger -t cloudflare "compressing $i"
done

# Find files older than 7 days
compressed_files=`find /var/log/cloudflare_logs -type f  ! -mtime -7`

# Remove old compressed files
for i in $compressed_files; do
  /bin/rm $i
  logger -t cloudflare "deleteing $i"
done
